services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - counter

  bot:
    build: ./bot
    volumes:
      - ./bot:/app
    environment:
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
    depends_on:
      - backend

  counter:
    build: ./counter
    ports:
      - "8081:8081"
    volumes:
      - ./counter:/app